config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :recipes, only: [:index, :show] do
    resources :steps, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :steps, dependent: :destroy
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @step = Step.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @step = Step.new(step_params)
    @step.recipe = @recipe
    if @step.save
      redirect_to recipe_path(@recipe)
    else
      render :new
    end
  end

  private

  def step_params
    params.require(:step).permit(:photo, :description, :ingredients)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipesApp757</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 pb-0 mx-auto">
    <div class="flex flex-col text-center w-full mb-20">
      <h2 class="text-xs text-purple-500 tracking-widest font-medium title-font mb-1">Recipe party</h2>
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">All recipes</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Find recipes that you'll love. We have everything you could ever dream of, including our specialty: RAW CHICKEN!</p>
    </div>
  </div>
</section>

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-wrap -m-4">
        <% @recipes.each do |recipe| %>
            <div class="p-4 md:w-1/3 no-underline">
                <%= link_to recipe_path(recipe), class:'block h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden no-underline' do %>
                    <img class="lg:h-48 md:h-36 w-full object-cover object-center" src="<%= recipe.photo %>" alt="blog">
                    <div class="p-6">
                        <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1 text-upcase"><%= recipe.difficulty %></h2>
                        <h1 class="title-font text-lg font-medium text-gray-900 mb-3"><%= recipe.name %></h1>
                        <p class="leading-relaxed mb-3">Photo booth fam kinfolk cold-pressed sriracha leggings jianbing microdosing tousled waistcoat.</p>
                        <div class="flex items-center flex-wrap ">
                        <div class="text-purple-500 inline-flex items-center md:mb-2 lg:mb-0">Learn More
                            <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path d="M5 12h14"></path>
                            <path d="M12 5l7 7-7 7"></path>
                            </svg>
                        </div>
                        <span class="text-gray-400 mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none text-sm pr-3 py-1 border-gray-200">
                            <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                            <path d="M12 17.75l-6.172 3.245l1.179 -6.873l-5 -4.867l6.9 -1l3.086 -6.253l3.086 6.253l6.9 1l-5 4.867l1.179 6.873z" />
                            </svg>
                            <%= recipe.rating %>
                        </span>
                        </div>
                    </div>
                <% end %>
            </div>
        <% end %>
    </div>
  </div>
</section>

app/views/recipes/show.html.erb
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="lg:w-1/2 w-full mb-10 lg:mb-0 rounded-lg overflow-hidden h-96">
      <img alt="feature" class="object-cover object-center h-full w-full" src="<%= @recipe.photo %>">
    </div>
    <div class="flex flex-col flex-wrap lg:py-6 -mb-10 lg:w-1/2 lg:pl-12">
      
        <h2 class="text-xs text-purple-500 tracking-widest font-medium title-font mb-1"><%= @recipe.difficulty %></h2>
        <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900 mb-10"><%= @recipe.name %></h1>
      
        <% @recipe.steps.each_with_index do |step, index| %>
            <div class="flex flex-col mb-10">
                <div class="w-12 h-12 inline-flex items-center justify-center rounded-full bg-purple-100 text-purple-500 mb-5">
                    <h4 class="text-purple-500 font-bold text-lg m-0"><%= index + 1 %></h4>
                </div>
                <div class="flex-grow">
                <%= image_tag step.photo, class: 'rounded-md w-full mb-4' %>
                <h2 class="text-gray-400 text-xs title-font font-medium mb-3"><%= step.ingredients %></h2>
                <p class="leading-relaxed text-base"><%= step.description %></p>
                </div>
            </div>
        <% end %>

        <%= link_to 'Add a new step', new_recipe_step_path(@recipe), class: 'mx-auto mt-16 text-white bg-purple-500 border-0 py-2 px-8 focus:outline-none hover:bg-purple-600 rounded text-lg w-full text-center' %>

    </div>
  </div>
</section>

app/views/steps/new.html.erb
<div class="max-w-xl p-10 mx-auto">
    <h1>Add a step</h1>
    <%= simple_form_for([@recipe, @step]) do |f| %>
        <%= f.input :photo %>
        <%= f.input :description %>
        <%= f.input :ingredients %>
        <%= f.submit 'Add step', class: "mx-auto mt-16 text-white bg-purple-500 border-0 py-2 px-8 focus:outline-none hover:bg-purple-600 rounded text-lg w-full text-center" %>
    <% end %>
</div>